### ISSUE TITLE
CSRF verification failed. Request aborted.

### ISSUE THREAD

**Issue by rzig** [digitalocean/netbox-docker#14]
Hi! I'm trying to login, but get the above error. I configured HTTPS in my nginx.conf file, and the login page loads successfully, but when I POST /login, I get a 403. Here's my Dockerfile:

```
FROM python:2.7-alpine

RUN apk add --no-cache \
      bash \
      build-base \
      ca-certificates \
      cyrus-sasl-dev \
      graphviz \
      jpeg-dev \
      libffi-dev \
      libxml2-dev \
      libxslt-dev \
      openldap-dev \
      openssl-dev \
      postgresql-dev \
      wget \
  && pip install gunicorn==17.5 django-auth-ldap

WORKDIR /opt

ARG BRANCH=v2-beta
ARG URL=https://github.com/digitalocean/netbox/archive/$BRANCH.tar.gz
RUN wget -q -O - "${URL}" | tar xz \
  && ln -s netbox* netbox

WORKDIR /opt/netbox
RUN pip install -r requirements.txt

RUN ln -s configuration.docker.py netbox/netbox/configuration.py
COPY docker/gunicorn_config.py /opt/netbox/
COPY docker/nginx.conf  /etc/netbox-nginx/nginx.conf
COPY docker/mycert.key /etc/netbox-nginx/mycert.key
COPY docker/mycert.pem /etc/netbox-nginx/mycert.pem

COPY docker/docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT [ "/docker-entrypoint.sh" ]

VOLUME ["/etc/netbox-nginx/"]
```
And then for my docker-compose.yml:
```
version: '3'
services:
    netbox:
        build: .
        image: digitalocean/netbox:v2.0-beta2
        depends_on:
        - postgres
        env_file: netbox.env
        volumes:
        - netbox-nginx-config:/etc/netbox-nginx/
        - netbox-static-files:/opt/netbox/netbox/static
        environment:
            DB_HOST: postgres
            DB_USER: netbox
            DB_PASSWORD: supersecret
            SECRET_KEY: supersecretkey
            LOGIN_REQUIRED: 1
            ALLOWED_HOSTS: '*'
    nginx:
        image: nginx:1.11-alpine
        command: nginx -g 'daemon off;' -c /etc/netbox-nginx/nginx.conf
        depends_on:
        - netbox
        ports:
        - 80
        - 443:443
        volumes:
        - netbox-static-files:/opt/netbox/netbox/static
        - netbox-nginx-config:/etc/netbox-nginx/
    postgres:
        image: postgres:9.6-alpine
        environment:
            POSTGRES_USER: netbox
            POSTGRES_PASSWORD: supersecret
            POSTGRES_DB: netbox
        volumes:
        - postgres-data:/var/lib/postgrelsql/data

volumes:
    netbox-static-files:
        driver: local
    netbox-nginx-config:
        driver: local
    postgres-data:
        driver: local
```
And lastly, my nginx.conf:
```
worker_processes 1;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    tcp_nopush     on;
    keepalive_timeout  65;
    gzip  on;
    server_tokens off;
    error_log /var/log/nginx/error.log;

    ssl on;
    ssl_certificate     /etc/netbox-nginx/mycert.pem;
    ssl_certificate_key /etc/netbox-nginx/mycert.key;
    ssl_protocols      TLSv1 TLSv1.1 TLSv1.2;
    ssl_ciphers        RC4:HIGH:!aNULL:!MD5;
    ssl_session_timeout 5m;
    ssl_prefer_server_ciphers on;

    server {
        listen 80;

        server_name localhost;
        rewrite ^ https://$host$request_uri? permanent;
    }
    server {
        listen 443 ssl;
        ssl on;
        server_name localhost;

        location /static/ {
            alias /opt/netbox/netbox/static/;
        }

        location / {
            proxy_pass http://netbox:8001;
            proxy_set_header X-Forwarded-Host $server_name;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header P3P 'CP="ALL DSP COR PSAa PSDa OUR NOR ONL UNI COM NAV"';
        }
    }
}
```
I also tried the following nginx configuration:
```
server {
        listen 80;

        server_name localhost;
        return 301 https://$host$request_uri;
    }
```

Both of these resulted in the CSRF error. There are no explanations in the console, just the following output:
```
[14/Jun/2017:21:38:37 +0000] "POST /login/ HTTP/1.1" 403 565 "https://10.10.5.23/login/?next=/" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) Gecko/20100101 Firefox/53.0"
```
This doesn't seem to say why the CSRF error is happening, just that it exists. Since it is already set up to allow all hosts, is there another setting I need to try? Tagging @jeremystretch who appears to be the lead maintainer of netbox and @cimnine who appears to be the lead maintainer of docker-netbox.
